<!DOCTYPE html>
<html lang="zh">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        /* ES2017 标准引入了 async 函数，使得异步操作变得更加方便。
            async是Generator的语法糖
             */
        //const fs = require('fs');

        const readFile = function (fileName) {
            return new Promise(function (resolve, reject) {
                fs.readFile(fileName, function (error, data) {
                    if (error) return reject(error);
                    resolve(data);
                });
            });
        };

        const gen = function* () {
            const f1 = yield readFile('/etc/fstab');
            const f2 = yield readFile('/etc/shells');
            console.log(f1.toString());
            console.log(f2.toString());
        };

        //用async改写
        const asyncReadFile = async function () {
            const f1 = await readFile('/etc/fstab');
            const f2 = await readFile('/etc/shells');
            console.log(f1.toString());
            console.log(f2.toString());
        };
        /*
        async函数就是将 Generator 函数的星号（*）替换成async，将yield替换成await，仅此而已。 

        特点
            - 内置执行器
                - async函数的执行，与普通函数一模一样，只要一行。
            - 更好的语义
                - async和await，比起星号和yield，语义更清楚了
                - async表示函数里有异步操作，await表示紧跟在后面的表达式需要等待结果。
            - 更广的适用性。
                - co模块约定，yield命令后面只能是 Thunk 函数或 Promise 对象，
                - 而async函数的await命令后面，可以是 Promise 对象和原始类型的值（数值、字符串和布尔值，但这时会自动转成立即 resolved 的 Promise 对象）。
            - 返回值是 Promise。
                - async函数的返回值是 Promise 对象，这比 Generator 函数的返回值是 Iterator 对象方便多了
                - async函数完全可以看作多个异步操作，包装成的一个 Promise 对象，而await命令就是内部then命令的语法糖。
         */
        /*
        基本用法
            async函数返回一个 Promise 对象，可以使用then方法添加回调函数。
            当函数执行的时候，一旦遇到await就会先返回，等到异步操作完成，再接着执行函数体内后面的语句。 
         */
        // async function getStockPriceByName(name) {
        //     const symbol = await getStockSymbol(name);
        //     const stockPrice = await getStockPrice(symbol);
        //     return stockPrice;
        // }
        //调用该函数时，会立即返回一个Promise对象
        // getStockPriceByName('goog').then(function (result) {
        //     console.log(result);
        // });
        //另一个例子
        function timeout(ms) {
            return new Promise((resolve) => {
                setTimeout(resolve, ms);
            });
        }

        async function asyncPrint(value, ms) {
            await timeout(ms);
            console.log(value);
        }

        asyncPrint('hello world', 50);
        //由于async函数返回的是一个promise,可以作为await命令的参数
        //上面的函数可以改写为
        async function timeout(ms) {
            await new Promise((resolve) => {
                setTimeout(resolve, ms);
            });
        }


        /* async 函数有多种使用形式 */
        // 函数声明
        async function foo() { }

        // 函数表达式
        const foo1 = async function () { };

        // 对象的方法
        let obj = { async foo() { } };
        obj.foo().then()

        // Class 的方法
        class Storage {
            constructor() {
                this.cachePromise = caches.open('avatars');
            }

            async getAvatar(name) {
                const cache = await this.cachePromise;
                return cache.match(`/avatars/${name}.jpg`);
            }
        }

        const storage = new Storage();
        //storage.getAvatar('jake').then(…);

        // 箭头函数
        //const foo = async () => { };


        /* 语法
        async函数返回一个promise对象
            async函数内部return语句返回的值,会成为then方法回调函数的参数 */
        async function f() {
            return 'hello world';
        }

        f().then(v => console.log(v))
        // "hello world"

        /* 
        async函数内部抛出错误，会导致返回的 Promise 对象变为reject状态。
        抛出的错误对象会被catch方法回调函数接收到。 */
        async function f1() {
            throw new Error('出错了');
        }

        f1().then(
            v => console.log('resolve', v),
            e => console.log('reject', e)
        )
        //reject Error: 出错了



        /*  Promise 对象的状态变化
                async函数返回的 Promise 对象，必须等到内部所有await命令后面的 Promise 对象执行完，
                才会发生状态改变，除非遇到return语句或者抛出错误.
                也就是说，只有async函数内部的异步操作执行完，才会执行then方法指定的回调函数。*/

        /* await 命令  
            await命令后面是一个 Promise 对象，返回该对象的结果。如果不是 Promise 对象，就直接返回对应的值。
            另一种情况是，await命令后面是一个thenable对象（即定义了then方法的对象），那么await会将其等同于 Promise 对象。*/
        async function f() {
            // 等同于
            // return 123;
            return await 123;
        }

        f().then(v => console.log(v))
        // 123      

        class Sleep {
            constructor(timeout) {
                this.timeout = timeout;
            }
            //定义了then()方法
            then(resolve, reject) {
                const startTime = Date.now();
                setTimeout(
                    () => resolve(Date.now() - startTime),
                    this.timeout
                );
            }
        }

        (async () => {
            const sleepTime = await new Sleep(1000);
            console.log(sleepTime);
        })();
        // 1000

        //JavaScript 一直没有休眠的语法，但是借助await命令就可以让程序停顿指定的时间。下面给出了一个简化的sleep实现。
        function sleep(interval) {
            return new Promise((resolve, reject) => {
                setTimeout(resolve, interval);
            })
        }
        //用法
        async function one2FiveInAsync() {
            for (let i = 0; i <= 5; i++) {
                console.log(i);
                await sleep(1000);
            }
        }
        one2FiveInAsync();



        /* await命令后面的 Promise 对象如果变为reject状态，则reject的参数会被catch方法的回调函数接收到。
         */

        /* 如果await后面的异步操作出错，那么等同于async函数返回的 Promise 对象被reject。 */


        /* 使用注意点
               - await命令后面的Promise对象，运行结果可能是rejected，所以最好把await命令放在try...catch代码块中。
               - 多个await命令后面的异步操作，如果不存在继发关系，最好让它们同时触发。 
               - ，await命令只能用在async函数之中，如果用在普通函数，就会报错
               - async 函数可以保留运行堆栈。*/
        async function myFunction() {
            try {
                await somethingThatReturnsAPromise();
            } catch (err) {
                console.log(err);
            }
        }
        // 另一种写法
        async function myFunction() {
            await somethingThatReturnsAPromise()
                .catch(function (err) {
                    console.log(err);
                });
        }

        let foo = await getFoo();
        let bar = await getBar();
        //改写为以下(同时触发)
        // 写法一
        let [foo, bar] = await Promise.all([getFoo(), getBar()]);

        // 写法二
        let fooPromise = getFoo();
        let barPromise = getBar();
        let foo = await fooPromise;
        let bar = await barPromise;


        //第四点
        const a = () => {
            b().then(() => c());
        };
        /*
        上面代码中，函数a内部运行了一个异步任务b()。当b()运行的时候，函数a()不会中断，
        而是继续执行。等到b()运行结束，可能a()早就运行结束了，
        b()所在的上下文环境已经消失了。如果b()或c()报错，错误堆栈将不包括a()。 
         */
        const a = async () => {
            await b();
            c();
        };
        /* 上面代码中，b()运行的时候，a()是暂停执行，上下文环境都保存着。
        一旦b()或c()报错，错误堆栈将包括a()。 */



        /* async 函数的实现原理 
            async 函数的实现原理，就是将 Generator 函数和自动执行器，包装在一个函数里。
             */
        async function fn(args) {
            // ...
        }

        // 等同于

        function fn(args) {
            return spawn(function* () {
                // ...
            });
        }//，其中的spawn函数就是自动执行器。
        function spawn(genF) {
            return new Promise(function (resolve, reject) {
                const gen = genF();
                function step(nextF) {
                    let next;
                    try {
                        next = nextF();
                    } catch (e) {
                        return reject(e);
                    }
                    if (next.done) {
                        return resolve(next.value);
                    }
                    Promise.resolve(next.value).then(function (v) {
                        step(function () { return gen.next(v); });
                    }, function (e) {
                        step(function () { return gen.throw(e); });
                    });
                }
                step(function () { return gen.next(undefined); });
            });
        }

    </script>
</body>

</html>